export const ADD_TO_USER_LIST="ADD_TO_USER_LIST"
export const REMOVE_TO_USER_LIST="REMOVE_TO_USER_LIST"

export const PRODUCT_LIST="PRODUCT_LIST"
export const SET_PRODUCT_LIST="SET_PRODUCT_LIST"

export const USER_FETCH_FAILED="USER_FETCH_FAILED"
export const PRODUCT_SEARCH="PRODUCT_SEARCH"

export const PRODUCT_FIND_BY_ID="PRODUCT_FIND_BY_ID"

export const PRODUCT_SET_BY_ID="PRODUCT_SET_BY_ID"